### ISSUE TITLE
backups...

### ISSUE THREAD

**Issue by carolinajoy76** [zhuowei/PocketInvEditor#22]
Does anyone know how to use the backup files from pocket inventory editor?  The new update in Minecraft put cavern and caves everywhere in my world but, only the people that join my world can see it.  Any help would be great. 
Thanks,
Joy

**Comment by zhuowei** [comment]
Pulled the entire backups feature from PocketInvEditor as it's broken above 0.7.1. If you have a backup made before 0.7.1, extract it using any file manager that can open Zips - they are stored in games/com.mojang/minecraftWorlds_backup
If you have Pro, there's a way to fix the world holes above 0.7.1; Edit Terrain -> fix world holes in multiplayer

**Comment by carolinajoy76** [comment]
Thank you for the fix it's awesome!!
