### ISSUE TITLE
backups fail

### ISSUE THREAD

**Issue by billym357** [zhuowei/PocketInvEditor#23]
The backups only create a player file. I lost my map now :( so much hard work and its all gone. Other then that the app is great

**Comment by carolinajoy76** [comment]
Same here.....after the new Minecraft update my world has new caverns, caves and holes everywhere but, only the people that join can see them.  We thought maybe we could rebuild the damage but i can not see the damage  and the repairs they make do not save. :P  So, i thought "I'm good i have my backups from pocket inventory editor"  NOT .....they don't work!!!!  Backup on sd from now on!

**Comment by zhuowei** [comment]
Backing up worlds created/modified after 0.7.0 is broken, I'm looking into it.

Backups of worlds created prior to 0.7.0 can be extracted with any file manager that supports ZIP - ES File Manager seems to work.

Edit: Astro works too.

**Comment by billym357** [comment]
I don't have any old backups of that world sadly. Is it possible for you to make it so we can make bigger worlds?

**Comment by zhuowei** [comment]
Broken backups feature removed, fix world holes in multiplayer feature added to the Pro version in 1.8.2.

**Comment by carolinajoy76** [comment]
Update fixed all my problems!  And the ES app did work on one of my older worlds.   You rock!  Thank you sooooo very much! !!!
Joy
