### ISSUE TITLE
please do

### ISSUE THREAD

**Issue by ZacharyCoss** [zhuowei/PocketInvEditor#26]
Can you get this app on apple products like ipod ,iphone ,iPad all that cause if you do you have a lot more happy people

**Comment by jonnyli1125** [comment]
apple products are too mainstream, this is android, the land of hipsters?!?!?

**Comment by zhuowei** [comment]
If you have a jailbroken device, I recommend EmendoMC. http://www.minecraftforum.net/topic/1836208-emendomc-ios-inventory-editor/
If you are not jailbroken, what are you waiting for?
