### ISSUE TITLE
nether spawn

### ISSUE THREAD

**Issue by p3op73** [zhuowei/PocketInvEditor#31]
ive heard all sorts spawn from it ive done it numerous times now but i havent seen a hostile, i know its random. also can it be active more than once coz ive tried it and it says active and turns red but not as before and stays red hoping itll still spawn something to kill :) but it dont yet its active. is it an issue or do i just be patient ive been on that survival map for a week and no baddies came for me :(  
  thank youuuu for the app btw :)

**Comment by zhuowei** [comment]
Refer to Minecraft Wiki for instructions on how to play MCPE: this is support for PocketInvEditor only.

**Comment by jonnyli1125** [comment]
zuwai hao 2 i play mcpe halp mi

**Comment by zhuowei** [comment]
@jonnyli1125 U FIRST ROOT UR PHONE, THEN U PLAY MIENCRAFT ON PHONE

**Comment by jonnyli1125** [comment]
@zhuowei THENX ZUWAI I PLY MCPE NOA
