### ISSUE TITLE
i know your all about minecraft.. as am i but....

### ISSUE THREAD

**Issue by milkbingus** [zhuowei/PocketInvEditor#35]
If you would consider doing a terraria inventory editor for the play store. I would kindly donate a hefty wager into your pay pal donations(if you have one)... I was trying to contract you via Dev email but couldn't find it.. Your mcpe editor is so clean and precise. I would love to see it for terraria. Gamekiller and gamechanger can be risky and confusing to some people if they don't know how to correctly find hotbar addresses.

**Comment by milkbingus** [comment]
Contact*

**Comment by milkbingus** [comment]
.......,sorry i didnt relize this was an issue forum

**Comment by jonnyli1125** [comment]
you're*

**Comment by zhuowei** [comment]
I shall look into it.
