### ISSUE TITLE
Compatibility with Minecraft Pocket Edition 0.9.0 alpha

### ISSUE THREAD

**Issue by themegaxandy** [zhuowei/PocketInvEditor#49]
Downloaded Minecraft Pocket Edition 0.9.0 alpha for my Android, and Pocket Inv Editor application can not edit more inventory.

**Comment by zhuowei** [comment]
You need the beta from http://zhuoweizhang.net/PocketInvEditor-app/PocketInvEditorApp-release-beta.apk
