### ISSUE TITLE
removes enchanted items when used

### ISSUE THREAD

**Issue by TahaTheHacker** [zhuowei/PocketInvEditor#64]
when i use PocketInvEditor my enchanted items become not enchanted. i hate that BUG

please fix and add enchantment ids slot

**Comment by zhuowei** [comment]
Thanks, will try to fix.

**Comment by zhuowei** [comment]
Fixed in latest beta: http://zhuoweizhang.net/PocketInvEditor-app/PocketInvEditorApp-release-beta.apk

**Comment by TahaTheHacker** [comment]
Thanks ,Owner of blockluancher :+1:
