### ISSUE TITLE
Issues with backup function

### ISSUE THREAD

**Issue by zhuowei** [zhuowei/PocketInvEditor#9]
The backup function seems to be creating slightly corrupt .zip files.

Output of 7zip when extracting:

<pre>
7z x PyMcLevel\ test2012-05-25-15-17.zip 

7-Zip 9.04 beta  Copyright (c) 1999-2009 Igor Pavlov  2009-05-30
p7zip Version 9.04 (locale=en_CA.UTF-8,Utf16=on,HugeFiles=on,1 CPU)

Processing archive: PyMcLevel test2012-05-25-15-17.zip

Extracting  entities.dat     Unsupported Method
Extracting  level.dat     Unsupported Method
Extracting  chunks.dat     Unsupported Method

Sub items Errors: 3</pre>

Output of unzip when extracting a backup:

<pre>$ unzip PyMcLevel\ test2012-05-25-15-17.zip 
Archive:  PyMcLevel test2012-05-25-15-17.zip
file #1 (entities.dat):
         mismatch between local and central GPF bit 11 ("UTF-8"),
         continuing with central flag (IsUTF8 = 0)
  inflating: entities.dat            
file #2 (level.dat):
         mismatch between local and central GPF bit 11 ("UTF-8"),
         continuing with central flag (IsUTF8 = 0)
  inflating: level.dat               
file #3 (chunks.dat):
         mismatch between local and central GPF bit 11 ("UTF-8"),
         continuing with central flag (IsUTF8 = 0)
  inflating: chunks.dat </pre>

Anyone know why this happens?

**Comment by machinamentum** [comment]
This seems to happen with the APKs that PocketTool creates. I believe there is a bug in Android's implementation of ZipOutputStream. It seems that Android can still interpret the APK correctly but the resulting APK cannot be unzipped by standard zip utilities.

**Comment by zhuowei** [comment]
Thanks for the feedback. I'll look into the 7Zip implementation for Java to see if that creates better zip files.

**Comment by zhuowei** [comment]
Backup feature removed in 1.8.2.
